/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        surface: '#f8f9ff',
        'surface-dim': '#cbdbf5',
        'surface-bright': '#f8f9ff',
        'surface-container-lowest': '#ffffff',
        'surface-container-low': '#eff4ff',
        'surface-container': '#e5eeff',
        'surface-container-high': '#dce9ff',
        'surface-container-highest': '#d3e4fe',
        'on-surface': '#0b1c30',
        'on-surface-variant': '#44474d',
        'inverse-surface': '#213145',
        'inverse-on-surface': '#eaf1ff',
        outline: '#75777e',
        'outline-variant': '#c5c6cd',
        'surface-tint': '#515f78',
        primary: '#000000',
        'on-primary': '#ffffff',
        'primary-container': '#0d1c32',
        'on-primary-container': '#76849f',
        'primary-fixed': '#d6e3ff',
        'primary-fixed-dim': '#b9c7e4',
        'on-primary-fixed': '#0d1c32',
        'on-primary-fixed-variant': '#39475f',
        secondary: '#4f5e80',
        'on-secondary': '#ffffff',
        'secondary-container': '#c7d7fe',
        'on-secondary-container': '#4e5d7e',
        'secondary-fixed': '#d8e2ff',
        'secondary-fixed-dim': '#b6c6ed',
        'on-secondary-fixed': '#091b39',
        'on-secondary-fixed-variant': '#374767',
        tertiary: '#000000',
        'on-tertiary': '#ffffff',
        'tertiary-container': '#002114',
        'on-tertiary-container': '#069669',
        'tertiary-fixed': '#85f8c4',
        'tertiary-fixed-dim': '#68dba9',
        'on-tertiary-fixed': '#002114',
        'on-tertiary-fixed-variant': '#005137',
        error: '#ba1a1a',
        'on-error': '#ffffff',
        'error-container': '#ffdad6',
        'on-error-container': '#93000a',
        background: '#f8fafc',
        'on-background': '#0f172a',
        'surface-variant': '#f1f5f9',
        lms: {
          sidebar: '#0b1727',
          active: '#162740',
          hover: '#112035',
          border: '#192b45',
          card: '#ffffff',
          bg: '#f8fafc',
          textMuted: '#8b9bb4',
        },
      },
      borderRadius: {
        none: '0px',
        sm: '0.25rem',
        DEFAULT: '0.375rem',
        md: '0.5rem',
        lg: '0.75rem',
        xl: '1rem',
        '2xl': '1.5rem',
        full: '9999px',
      },
      fontFamily: {
        display: ['"Space Grotesk"', 'sans-serif'],
        'headline-lg': ['"Space Grotesk"', 'sans-serif'],
        'headline-md': ['"Space Grotesk"', 'sans-serif'],
        'headline-sm': ['"Space Grotesk"', 'sans-serif'],
        'body-lg': ['Geist', 'sans-serif'],
        'body-md': ['Geist', 'sans-serif'],
        'body-sm': ['Geist', 'sans-serif'],
        'label-md': ['Geist', 'sans-serif'],
        'label-sm': ['Geist', 'sans-serif'],
      },
      spacing: {
        'space-xs': '0.25rem',
        'space-sm': '0.5rem',
        'space-md': '1rem',
        'space-lg': '1.5rem',
        'space-xl': '2.5rem',
        gutter: '1.5rem',
        'gutter-mobile': '1rem',
        margin: '3rem',
        'margin-mobile': '1.25rem',
      },
    },
  },
  plugins: [],
};
